import localFont from "next/font/local";
import {Montserrat} from "next/font/google"
import "./globals.css";


import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


const montSerrat = Montserrat({
  subsets:['latin'],
  weight:["100","200","300","400","500","600","700","800","900"],
  variable:"--font-Monsterrat",
}); 

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={montSerrat.variable}>
        <Header/>
        <StairTransition/>
        <PageTransition/>
      
        {children}
      </body>
    </html>
  );
}
